// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAVEFguxi73wlCK0XualaHy2G2wdJ3MQ4',
    appId: '1:464501085820:web:974dc96f74049317449bf9',
    messagingSenderId: '464501085820',
    projectId: 'inhomex-0219',
    authDomain: 'inhomex-0219.firebaseapp.com',
    storageBucket: 'inhomex-0219.appspot.com',
    measurementId: 'G-2XZF76C69X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD2-hDK1xA2YcCdJc1Z5AM93hm9vAlxAQ',
    appId: '1:464501085820:android:b9caae80737d0d94449bf9',
    messagingSenderId: '464501085820',
    projectId: 'inhomex-0219',
    storageBucket: 'inhomex-0219.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIf-ZJMZfCRt3NH7Mk1qErlmecsQA68w0',
    appId: '1:464501085820:ios:383a0fef86e63c0b449bf9',
    messagingSenderId: '464501085820',
    projectId: 'inhomex-0219',
    storageBucket: 'inhomex-0219.appspot.com',
    iosBundleId: 'com.example.inhomex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIf-ZJMZfCRt3NH7Mk1qErlmecsQA68w0',
    appId: '1:464501085820:ios:383a0fef86e63c0b449bf9',
    messagingSenderId: '464501085820',
    projectId: 'inhomex-0219',
    storageBucket: 'inhomex-0219.appspot.com',
    iosBundleId: 'com.example.inhomex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAVEFguxi73wlCK0XualaHy2G2wdJ3MQ4',
    appId: '1:464501085820:web:4e60e60a09526c89449bf9',
    messagingSenderId: '464501085820',
    projectId: 'inhomex-0219',
    authDomain: 'inhomex-0219.firebaseapp.com',
    storageBucket: 'inhomex-0219.appspot.com',
    measurementId: 'G-6TKJ89K7G5',
  );

}